apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: regalia
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  writeBackConfig:
    method: git
    gitConfig:
      repository: git@github.com:ictsc/ictsc-k8s-dev.git
      branch: main
      writeBackTarget: kustomization:/manifest/base/apps/regalia/workload/overlays/dev
  applicationRefs:
    - namePattern: regalia
      images:
        - alias: backend
          imageName: ghcr.io/ictsc/ictsc-regalia/backend:sha-44aa601
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: regexp:^sha-[0-9a-f]{7,40}$
          manifestTargets:
            kustomize:
              name: ghcr.io/ictsc/ictsc-regalia/backend
        - alias: frontend
          imageName: ghcr.io/ictsc/ictsc-regalia/frontend:sha-44aa601
          commonUpdateSettings:
            updateStrategy: newest-build
            allowTags: regexp:^sha-[0-9a-f]{7,40}$
          manifestTargets:
            kustomize:
              name: ghcr.io/ictsc/ictsc-regalia/frontend
