apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: regalia
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  sourceRepos:
    - git@github.com:ictsc/ictsc-k8s-dev.git
    - https://cloudnative-pg.github.io/charts
    - https://valkey.io/valkey-helm/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: scoreserver
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
