#!/usr/bin/env python3
"""Render non-secret Discord env config. Requires PyYAML; does not modify teams in DB."""
import json
from pathlib import Path
import yaml

root = Path(__file__).resolve().parents[2]
data = yaml.safe_load((root / 'config/regalia/dev-discord-teams.yaml').read_text())
roles = {}
codes = set()
names = set()
for team in data['teams']:
    role, code = team['discord_role']['id'], team['code']
    assert isinstance(role, str) and role.isdecimal(), 'Role IDs must be decimal strings'
    assert 2 <= code <= 99 and code not in codes and role not in roles, 'Duplicate/invalid team mapping'
    assert team['name'] == team['discord_role']['name'] and team['name'] not in names
    codes.add(code)
    names.add(team['name'])
    roles[role] = code
assert data['admin_role']['id'] not in roles, 'Staff role cannot register contestants'
values = {
    'ICTSC_DISCORD_CONTESTANT_GUILD_ID': data['guild']['id'],
    'ICTSC_DISCORD_ADMIN_GUILD_ID': data['guild']['id'],
    'ICTSC_DISCORD_ADMIN_ROLE_IDS': data['admin_role']['id'],
    'ICTSC_DISCORD_ROLE_TEAMS': json.dumps(roles, separators=(',', ':')),
}
path = root / 'manifest/base/apps/regalia/workload/overlays/openapi-dev/discord.env'
path.write_text('# Generated by scripts/regalia/render-discord-teams.py\n' + ''.join(f'{k}={v}\n' for k, v in values.items()))
print(f'Rendered {len(roles)} team roles')
