#!/usr/bin/env python3
"""Render idempotent prod demo bootstrap data (no participants or sessions)."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
data = json.loads((root / 'config/regalia/prod-demo-content.json').read_text())

def literal(value):
    return "'" + str(value).replace("'", "''") + "'"

snapshot = data['snapshot']
rows = ',\n'.join('(' + ','.join(literal(t[k]) for k in ('code','name','organization','member_limit','color')) + ')' for t in data['teams'])
sql = f'''-- Generated by scripts/regalia/render-prod-demo-seed.py.
-- Bootstrap only: preserve existing teams, active content, and edited rules.
BEGIN;
INSERT INTO teams (code,name,organization,member_limit,color) VALUES
{rows}
ON CONFLICT DO NOTHING;
INSERT INTO content_snapshots (commit_sha,repository,git_ref,manifest,fetched_at,activated_at,active)
SELECT {literal(snapshot['commit_sha'])},{literal(snapshot['repository'])},{literal(snapshot['git_ref'])},{literal(json.dumps(snapshot['manifest'],ensure_ascii=False))}::jsonb,now(),now(),true
WHERE NOT EXISTS (SELECT 1 FROM content_snapshots)
ON CONFLICT DO NOTHING;
UPDATE competition_state SET rule_markdown={literal(data['rules'])},updated_at=now(),updated_by='prod-demo-bootstrap'
WHERE singleton AND rule_markdown='';
COMMIT;
'''
(root / 'manifest/base/apps/regalia/workload/overlays/openapi-prod/0003_demo_seed.sql').write_text(sql)
