resources:
  - ../../base
  - ./resources/cilium-lb-ip-pool.yaml
  - ./resources/cilium-l2-announcement.yaml
  - ./resources/gateway.yaml
  - ./resources/cluster-issuer.yaml
  - ./resources/storageclass-nfs.yaml
  - ./resources/alertmanager-discord.yaml
  - ./resources/rbac-oidc.yaml
  - ./resources/httproutes.yaml

patches:
  - target: {kind: Application, name: cilium}
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/manifest/envs/prod/values/cilium.yaml
  - target: {kind: Application, name: kube-prometheus-stack}
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/manifest/envs/prod/values/kube-prometheus-stack.yaml
  - target: {kind: Application, name: argocd}
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/manifest/envs/prod/values/argocd.yaml
  - target: {kind: Application, name: dex}
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/manifest/envs/prod/values/dex.yaml
  - target: {kind: Application, name: oauth2-proxy}
    patch: |-
      - op: add
        path: /spec/sources/0/helm/valueFiles/-
        value: $values/manifest/envs/prod/values/oauth2-proxy.yaml
  - target: {kind: Application, name: regalia}
    patch: |-
      - op: replace
        path: /spec/source/path
        value: manifest/base/apps/regalia/workload/overlays/prod
  - target: {kind: ImageUpdater, name: regalia}
    patch: |-
      - op: replace
        path: /spec/writeBackConfig/gitConfig/writeBackTarget
        value: kustomization:/manifest/base/apps/regalia/workload/overlays/prod
      - op: replace
        path: /spec/applicationRefs/0/images/0/commonUpdateSettings/updateStrategy
        value: semver
      - op: replace
        path: /spec/applicationRefs/0/images/0/commonUpdateSettings/allowTags
        value: 'regexp:^v[0-9]+\.[0-9]+\.[0-9]+$'
      - op: replace
        path: /spec/applicationRefs/0/images/1/commonUpdateSettings/updateStrategy
        value: semver
      - op: replace
        path: /spec/applicationRefs/0/images/1/commonUpdateSettings/allowTags
        value: 'regexp:^v[0-9]+\.[0-9]+\.[0-9]+$'
