apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://oauth2-proxy.github.io/manifests
      chart: oauth2-proxy
      targetRevision: 10.7.0
      helm:
        releaseName: oauth2-proxy
        valueFiles:
          - $values/manifest/base/oauth2-proxy/values.yaml
          - $values/manifest/envs/prod/values/oauth2-proxy.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
