resources:
- backend.yaml
- frontend.yaml
- route-contestant.yaml
- route-admin.yaml
- migrate.yaml
namespace: scoreserver
images:
- name: backend
  newName: ghcr.io/ictsc/ictsc-regalia/backend
  digest: sha256:e1115066959d25389a9e1e00c4f81315076fa5d64a4af7ad4cc65cf59a2d0f78
  newTag: preview-openapi-20260910-2
- name: frontend
  newName: ghcr.io/ictsc/ictsc-regalia/frontend
  digest: sha256:961178c1ba4ce06e9b63309bebd059cee15a414f0e135f202d8dddacfa68322f
  newTag: preview-openapi-20260910-2
configMapGenerator:
- name: scoreserver-openapi-migrations
  files:
  - 0001_init.sql
  - 0002_team_color.sql
  options:
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: '-2'
