resources:
- backend.yaml
- frontend.yaml
- route-contestant.yaml
- route-admin.yaml
- migrate.yaml
namespace: scoreserver
images:
- name: backend
  newName: ghcr.io/ictsc/ictsc-regalia/backend
  digest: sha256:15fbf794d13b82d218c8a4b411c814b0f4baea1004901cb456f01b067b8448af
  newTag: preview-openapi-20260910-3
- name: frontend
  newName: ghcr.io/ictsc/ictsc-regalia/frontend
  digest: sha256:704511856f56b9716042913f9a19926233859697d7bb67d6578a2724c4ddbe7d
  newTag: preview-openapi-20260910-3
configMapGenerator:
- name: scoreserver-openapi-migrations
  files:
  - 0001_init.sql
  - 0002_team_color.sql
  options:
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: '-2'
- name: scoreserver-discord-teams
  envs:
  - discord.env
