resources:
- backend.yaml
- frontend.yaml
- route-contestant.yaml
- route-admin.yaml
- migrate.yaml
namespace: scoreserver
images:
- name: backend
  newName: ghcr.io/ictsc/ictsc-regalia/backend
  digest: sha256:2836f60d3ae1f146ee7915cc6bba5b8e84f113d80e96c643a7ffe379920bd8b5
  newTag: sha-0cefe73
- name: frontend
  newName: ghcr.io/ictsc/ictsc-regalia/frontend
  digest: sha256:84954fa6d397574df7359798057ba72ffe9b3198391374fed857b06b2058441e
  newTag: sha-0cefe73
configMapGenerator:
- name: scoreserver-openapi-migrations
  files:
  - 0001_init.sql
  - 0002_team_color.sql
  options:
    annotations:
      argocd.argoproj.io/hook: PreSync
      argocd.argoproj.io/sync-wave: '-2'
- name: scoreserver-discord-teams
  envs:
  - discord.env
