apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: sakura-secret-manager
spec:
  conditions:
    - namespaces:
        - dex
        - oauth2-proxy
        - argocd
        - monitoring
        - scoreserver
  provider:
    webhook:
      url: 'https://secure.sakura.ad.jp/cloud/zone/is1a/api/cloud/1.1/secretmanager/vaults/{{ .auth.vaultID }}/secrets/unveil'
      method: POST
      timeout: 10s
      headers:
        Content-Type: application/json
        Authorization: 'Basic {{ print .auth.token ":" .auth.secret | b64enc }}'
      body: '{"Secret":{"Name":{{ .remoteRef.key | toJson }}}}'
      result:
        jsonPath: $.Secret.Value
      secrets:
        - name: auth
          secretRef:
            name: sakura-secret-manager-credentials
            namespace: external-secrets
