resources:
  - ../../base

namespace: scoreserver

images:
  - name: backend
    newName: ghcr.io/ictsc/ictsc-regalia/backend
    newTag: sha-f19af1e
  - name: frontend
    newName: ghcr.io/ictsc/ictsc-regalia/frontend
    newTag: sha-f19af1e
  - name: toolbox
    newName: ghcr.io/ictsc/ictsc-regalia/toolbox
    newTag: sha-f19af1e

patches:
  - path: httproute-patch.yaml
  - path: secret-provider-patch.yaml

replicas:
  - name: scoreserver-backend
    count: 2
  - name: scoreserver-frontend
    count: 2
