resources:
  - ./infra/cilium/application.yaml
  - ./infra/cert-manager/application.yaml
  - ./infra/kubelet-serving-cert-approver/application.yaml
  - ./infra/csi-driver-nfs/application.yaml
  - ./infra/secrets-store-csi-driver/application.yaml
  - ./infra/kube-prometheus-stack/application.yaml
  - ./infra/loki/application.yaml
  - ./infra/alloy/application.yaml
  - ./infra/metrics-server/application.yaml
  - ./infra/argocd/application.yaml
  - ./infra/cloudnative-pg/application.yaml
  - ./infra/argocd-image-updater/application.yaml
  - ./infra/dex/application.yaml
  - ./infra/oauth2-proxy/application.yaml
  - ./apps/httpbin/application.yaml
  - ./apps/regalia/project.yaml
  - ./apps/regalia/postgres/application.yaml
  - ./apps/regalia/valkey/application.yaml
  - ./apps/regalia/application.yaml
  - ./apps/regalia/image-updater.yaml
