// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v7.36.0
// source: api/spec/machine.proto

package spec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MachineSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zone          string                 `protobuf:"bytes,1,opt,name=zone,proto3" json:"zone,omitempty"`
	ServerId      string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	DiskIds       []string               `protobuf:"bytes,3,rep,name=disk_ids,json=diskIds,proto3" json:"disk_ids,omitempty"`
	CdromId       string                 `protobuf:"bytes,4,opt,name=cdrom_id,json=cdromId,proto3" json:"cdrom_id,omitempty"`
	ExternalIp    string                 `protobuf:"bytes,5,opt,name=external_ip,json=externalIp,proto3" json:"external_ip,omitempty"`
	InternalIp    string                 `protobuf:"bytes,6,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineSpec) Reset() {
	*x = MachineSpec{}
	mi := &file_api_spec_machine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineSpec) ProtoMessage() {}

func (x *MachineSpec) ProtoReflect() protoreflect.Message {
	mi := &file_api_spec_machine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineSpec.ProtoReflect.Descriptor instead.
func (*MachineSpec) Descriptor() ([]byte, []int) {
	return file_api_spec_machine_proto_rawDescGZIP(), []int{0}
}

func (x *MachineSpec) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *MachineSpec) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MachineSpec) GetDiskIds() []string {
	if x != nil {
		return x.DiskIds
	}
	return nil
}

func (x *MachineSpec) GetCdromId() string {
	if x != nil {
		return x.CdromId
	}
	return ""
}

func (x *MachineSpec) GetExternalIp() string {
	if x != nil {
		return x.ExternalIp
	}
	return ""
}

func (x *MachineSpec) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

var File_api_spec_machine_proto protoreflect.FileDescriptor

const file_api_spec_machine_proto_rawDesc = "" +
	"\n" +
	"\x16api/spec/machine.proto\x12\x14sakura.provider.spec\"\xb6\x01\n" +
	"\vMachineSpec\x12\x12\n" +
	"\x04zone\x18\x01 \x01(\tR\x04zone\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x19\n" +
	"\bdisk_ids\x18\x03 \x03(\tR\adiskIds\x12\x19\n" +
	"\bcdrom_id\x18\x04 \x01(\tR\acdromId\x12\x1f\n" +
	"\vexternal_ip\x18\x05 \x01(\tR\n" +
	"externalIp\x12\x1f\n" +
	"\vinternal_ip\x18\x06 \x01(\tR\n" +
	"internalIpBDZBgithub.com/ictsc/ictsc-k8s-dev/omni/infra-provider-sakura/api/specb\x06proto3"

var (
	file_api_spec_machine_proto_rawDescOnce sync.Once
	file_api_spec_machine_proto_rawDescData []byte
)

func file_api_spec_machine_proto_rawDescGZIP() []byte {
	file_api_spec_machine_proto_rawDescOnce.Do(func() {
		file_api_spec_machine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_spec_machine_proto_rawDesc), len(file_api_spec_machine_proto_rawDesc)))
	})
	return file_api_spec_machine_proto_rawDescData
}

var file_api_spec_machine_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_spec_machine_proto_goTypes = []any{
	(*MachineSpec)(nil), // 0: sakura.provider.spec.MachineSpec
}
var file_api_spec_machine_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_spec_machine_proto_init() }
func file_api_spec_machine_proto_init() {
	if File_api_spec_machine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_spec_machine_proto_rawDesc), len(file_api_spec_machine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_spec_machine_proto_goTypes,
		DependencyIndexes: file_api_spec_machine_proto_depIdxs,
		MessageInfos:      file_api_spec_machine_proto_msgTypes,
	}.Build()
	File_api_spec_machine_proto = out.File
	file_api_spec_machine_proto_goTypes = nil
	file_api_spec_machine_proto_depIdxs = nil
}
