# このファイルは `task render-env-values` が terraform output から生成する
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: external
  annotations:
    argocd.argoproj.io/sync-wave: "-25"
spec:
  blocks:
    - start: 27.133.146.104
      stop: 27.133.146.104
