apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      path: charts/sakura-secrets
      helm:
        releaseName: dex-secrets
        valueFiles:
          - $values/manifest/envs/dev/secrets/dex.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: dex
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      path: charts/sakura-secrets
      helm:
        releaseName: oauth2-proxy-secrets
        valueFiles:
          - $values/manifest/envs/dev/secrets/oauth2-proxy.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      path: charts/sakura-secrets
      helm:
        releaseName: argocd-secrets
        valueFiles:
          - $values/manifest/envs/dev/secrets/argocd.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      path: charts/sakura-secrets
      helm:
        releaseName: monitoring-secrets
        valueFiles:
          - $values/manifest/envs/dev/secrets/monitoring.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
