apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: regalia-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: regalia
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cluster
      targetRevision: 0.8.1
      helm:
        releaseName: postgres
        valueFiles:
          - $values/manifest/base/apps/regalia/postgres/values.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: scoreserver
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    automated:
      prune: true
      selfHeal: true
