resources:
  - ./backend.yaml
  - ./frontend.yaml
  - ./httproute.yaml
  - ./migrate.yaml
  - ./discord-oauth-dummy.yaml

configMapGenerator:
  - name: scoreserver-backend-config
    files:
      - admin-auth-config.yaml
      - admin-auth-policy.csv

labels:
  - pairs:
      app.kubernetes.io/part-of: regalia
