# Argo CD 自身も Argo CD で管理する (self-managed)
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 10.2.3
      helm:
        releaseName: argocd
        valueFiles:
          - $values/manifest/base/infra/argocd/values.yaml
    - repoURL: git@github.com:ictsc/ictsc-k8s-dev.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: false # 自分自身を消してしまわないように prune は切っておく
      selfHeal: true
